language: python
sudo: false
python:
  - "3.6"
  - "3.7"
install:
  - pip install flake8
  - pip install coveralls
script:
  - flake8 greek_normalisation
  - coverage run --branch -m doctest tests.rst
after_success:
  - coveralls
